In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)

# ==================================================
# CAMPUS CONFIGURATION
# ==================================================

locations = [
    ("MAIN_BLOCK", "GROUND", "Library"),
    ("MAIN_BLOCK", "GROUND", "Chemistry Lab"),
    ("MAIN_BLOCK", "GROUND", "Classroom"),
    ("MAIN_BLOCK", "FLOOR1", "Auditorium"),
    ("MAIN_BLOCK", "FLOOR1", "Classroom"),
    ("MAIN_BLOCK", "FLOOR2", "Code Studio"),
    ("MAIN_BLOCK", "FLOOR2", "IT Project Lab"),
    ("MAIN_BLOCK", "FLOOR2", "Computer Lab"),
    ("MAIN_BLOCK", "FLOOR3", "Cybernet Lab"),
    ("MAIN_BLOCK", "FLOOR3", "Classroom"),

    ("MECH_BLOCK", "GROUND", "FABLAB"),
    ("MECH_BLOCK", "GROUND", "CAD Lab"),
    ("MECH_BLOCK", "GROUND", "Lab"),
    ("MECH_BLOCK", "FLOOR1", "Classroom"),
    ("MECH_BLOCK", "FLOOR2", "Library"),
    ("MECH_BLOCK", "FLOOR2", "Lab"),
    ("MECH_BLOCK", "FLOOR3", "Lab"),

    ("AI_BLOCK", "GROUND", "Robospace"),
    ("AI_BLOCK", "GROUND", "AI Lab"),
    ("AI_BLOCK", "FLOOR1", "ML Lab"),
    ("AI_BLOCK", "FLOOR1", "Classroom"),
    ("AI_BLOCK", "FLOOR2", "GenAI Lab"),
    ("AI_BLOCK", "FLOOR2", "Synapse Studio"),
    ("AI_BLOCK", "FLOOR2", "Vista Hall"),
    ("AI_BLOCK", "FLOOR2", "Classroom"),
    ("AI_BLOCK", "FLOOR3", "Cyber Lab"),
    ("AI_BLOCK", "FLOOR3", "Data Visualization Lab"),

    ("AMENITY", "GROUND", "Food Court"),
    ("AMENITY", "GROUND", "Music Room"),

    ("MARIO", "GROUND", "Snack Corner"),

    ("HOSTEL_BOYS", "GROUND", "Hostel"),
    ("HOSTEL_GIRLS", "GROUND", "Hostel"),

    ("BUS_AREA", "GROUND", "Bus Bay")
]

events = [
    "No_Event",
    "No_Event",
    "No_Event",
    "No_Event",
    "No_Event",
    "Thiran",
    "Freshwarite",
    "Culturals",
    "FlashMob"
]

weather_conditions = [
    "Sunny",
    "Cloudy",
    "Rainy"
]

rows = []

# ==================================================
# GENERATE 10,000 RECORDS
# ==================================================

for i in range(10000):

    building, floor, zone = locations[
        np.random.randint(0, len(locations))
    ]

    timestamp = pd.Timestamp("2025-01-01") + pd.to_timedelta(
        np.random.randint(0, 365*24*60),
        unit="m"
    )

    hour = timestamp.hour

    weather = np.random.choice(weather_conditions)

    event = np.random.choice(events)

    # ==================================================
    # BASE USERS
    # ==================================================

    users = np.random.randint(40, 120)

    # Academic hours

    if building in ["MAIN_BLOCK", "AI_BLOCK", "MECH_BLOCK"]:

        if 9 <= hour <= 12:
            users += np.random.randint(50, 120)

        elif 13 <= hour <= 16:
            users += np.random.randint(30, 90)

    # Lunch rush

    if building in ["AMENITY", "MARIO"]:

        if 12 <= hour <= 14:
            users += np.random.randint(80, 180)

    # Hostel rush

    if building in ["HOSTEL_BOYS", "HOSTEL_GIRLS"]:

        if 18 <= hour <= 23:
            users += np.random.randint(100, 250)

    # Events

    if event != "No_Event":

        if zone in [
            "Auditorium",
            "Vista Hall",
            "Food Court",
            "Synapse Studio"
        ]:
            users += np.random.randint(100, 250)

    # ==================================================
    # NETWORK METRICS
    # ==================================================

    bandwidth_usage = round(
        users * np.random.uniform(6, 15),
        2
    )

    download_speed = round(
        max(8, 150 - users * 0.55),
        2
    )

    upload_speed = round(
        max(5, 75 - users * 0.25),
        2
    )

    latency = round(
        8 + users * 0.65,
        2
    )

    packet_loss = round(
        min(
            15,
            np.random.uniform(0.5, 2.5)
            + users * 0.02
        ),
        2
    )

    signal_strength = np.random.randint(
        -80,
        -35
    )

    # ==================================================
    # TARGET
    # ==================================================

    if users < 100:
        congestion = "Low"

    elif users < 180:
        congestion = "Medium"

    else:
        congestion = "High"

    rows.append([
        i+1,
        timestamp,
        building,
        floor,
        zone,
        users,
        bandwidth_usage,
        download_speed,
        upload_speed,
        latency,
        packet_loss,
        signal_strength,
        weather,
        event,
        congestion
    ])

# ==================================================
# DATAFRAME
# ==================================================

columns = [
    "Record_ID",
    "Timestamp",
    "Building",
    "Floor",
    "Zone",
    "Connected_Users",
    "Bandwidth_Usage_MB",
    "Download_Speed_Mbps",
    "Upload_Speed_Mbps",
    "Latency_ms",
    "Packet_Loss_Percent",
    "Signal_Strength_dBm",
    "Weather",
    "Event_Occurring",
    "Congestion_Status"
]

df = pd.DataFrame(rows, columns=columns)

# ==================================================
# ADD MISSING VALUES
# ==================================================

download_missing = np.random.choice(
    df.index,
    size=300,
    replace=False
)

df.loc[
    download_missing,
    "Download_Speed_Mbps"
] = np.nan

signal_missing = np.random.choice(
    df.index,
    size=200,
    replace=False
)

df.loc[
    signal_missing,
    "Signal_Strength_dBm"
] = np.nan

# ==================================================
# ADD DUPLICATES
# ==================================================

duplicates = df.sample(
    200,
    random_state=42
)

df = pd.concat(
    [df, duplicates],
    ignore_index=True
)

# ==================================================
# SAVE
# ==================================================

df.to_csv(
    "campus_wifi_logs.csv",
    index=False
)

print("="*60)
print("DATASET GENERATED SUCCESSFULLY")
print("="*60)

print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

print("\nCongestion Distribution:")
print(df["Congestion_Status"].value_counts())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nFirst 5 Rows:")
display(df.head())

============================================================
DATASET GENERATED SUCCESSFULLY
============================================================
Rows: 10200
Columns: 15

Congestion Distribution:
Congestion_Status
Low       5156
Medium    3732
High      1312
Name: count, dtype: int64

Missing Values:
Record_ID                0
Timestamp                0
Building                 0
Floor                    0
Zone                     0
Connected_Users          0
Bandwidth_Usage_MB       0
Download_Speed_Mbps    307
Upload_Speed_Mbps        0
Latency_ms               0
Packet_Loss_Percent      0
Signal_Strength_dBm    205
Weather                  0
Event_Occurring          0
Congestion_Status        0
dtype: int64

Duplicate Rows:
200

First 5 Rows:

,Record_ID,Timestamp,Building,Floor,Zone,Connected_Users,Bandwidth_Usage_MB,Download_Speed_Mbps,Upload_Speed_Mbps,Latency_ms,Packet_Loss_Percent,Signal_Strength_dBm,Weather,Event_Occurring,Congestion_Status
0,1,2025-09-12 01:18:00,AMENITY,GROUND,Music Room,100,1137.17,95.00,50.00,73.00,3.39,-58.0,Rainy,Culturals,Medium
1,2,2025-03-02 18:18:00,MECH_BLOCK,GROUND,FABLAB,63,747.05,115.35,59.25,48.95,1.87,-57.0,Sunny,No_Event,Low
2,3,2025-05-19 05:21:00,MARIO,GROUND,Snack Corner,115,1323.06,86.75,46.25,82.75,2.81,NaN,Sunny,No_Event,Medium
3,4,2025-04-19 20:10:00,AI_BLOCK,FLOOR3,Data Visualization Lab,94,1395.81,98.30,51.50,69.10,3.31,-44.0,Rainy,No_Event,Low
4,5,2025-12-06 22:12:00,MAIN_BLOCK,FLOOR2,IT Project Lab,57,828.78,118.65,60.75,45.05,3.57,-72.0,Sunny,Freshwarite,Low

In [ ]:
print(df['Congestion_Status'].value_counts())

print(df['Event_Occurring'].value_counts())

print(df.isnull().sum())

Congestion_Status
Low       5156
Medium    3732
High      1312
Name: count, dtype: int64
Event_Occurring
No_Event       5670
Thiran         1158
FlashMob       1140
Culturals      1122
Freshwarite    1110
Name: count, dtype: int64
Record_ID                0
Timestamp                0
Building                 0
Floor                    0
Zone                     0
Connected_Users          0
Bandwidth_Usage_MB       0
Download_Speed_Mbps    307
Upload_Speed_Mbps        0
Latency_ms               0
Packet_Loss_Percent      0
Signal_Strength_dBm    205
Weather                  0
Event_Occurring          0
Congestion_Status        0
dtype: int64

# Campus Connectivity Intelligence System

## Section 1: Data Ingestion Using Pandas

In this section, the WiFi connectivity dataset is loaded into a Pandas DataFrame.

The dataset contains network usage logs collected from various locations across the campus, including academic blocks, hostels, food courts, libraries, laboratories, and event venues.

The objective is to understand the structure of the dataset before performing data cleaning and preprocessing.

In [ ]:
import pandas as pd
import numpy as np

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [ ]:
df = pd.read_csv("campus_wifi_logs.csv")

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [ ]:
print("="*60)
print("DATASET SHAPE")
print("="*60)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

============================================================
DATASET SHAPE
============================================================
Rows    : 10200
Columns : 15

In [ ]:
print("="*60)
print("FIRST 5 RECORDS")
print("="*60)

display(df.head())

============================================================
FIRST 5 RECORDS
============================================================

,Record_ID,Timestamp,Building,Floor,Zone,Connected_Users,Bandwidth_Usage_MB,Download_Speed_Mbps,Upload_Speed_Mbps,Latency_ms,Packet_Loss_Percent,Signal_Strength_dBm,Weather,Event_Occurring,Congestion_Status
0,1,2025-09-12 01:18:00,AMENITY,GROUND,Music Room,100,1137.17,95.00,50.00,73.00,3.39,-58.0,Rainy,Culturals,Medium
1,2,2025-03-02 18:18:00,MECH_BLOCK,GROUND,FABLAB,63,747.05,115.35,59.25,48.95,1.87,-57.0,Sunny,No_Event,Low
2,3,2025-05-19 05:21:00,MARIO,GROUND,Snack Corner,115,1323.06,86.75,46.25,82.75,2.81,NaN,Sunny,No_Event,Medium
3,4,2025-04-19 20:10:00,AI_BLOCK,FLOOR3,Data Visualization Lab,94,1395.81,98.30,51.50,69.10,3.31,-44.0,Rainy,No_Event,Low
4,5,2025-12-06 22:12:00,MAIN_BLOCK,FLOOR2,IT Project Lab,57,828.78,118.65,60.75,45.05,3.57,-72.0,Sunny,Freshwarite,Low

In [ ]:
print("="*60)
print("LAST 5 RECORDS")
print("="*60)

display(df.tail())

============================================================
LAST 5 RECORDS
============================================================

,Record_ID,Timestamp,Building,Floor,Zone,Connected_Users,Bandwidth_Usage_MB,Download_Speed_Mbps,Upload_Speed_Mbps,Latency_ms,Packet_Loss_Percent,Signal_Strength_dBm,Weather,Event_Occurring,Congestion_Status
10195,4517,2025-02-22 00:14:00,AI_BLOCK,FLOOR2,Vista Hall,110,1336.82,89.50,47.50,79.50,3.60,-52.0,Rainy,No_Event,Medium
10196,1262,2025-03-18 13:14:00,MAIN_BLOCK,FLOOR2,Code Studio,119,1255.48,84.55,45.25,85.35,3.71,-66.0,Cloudy,No_Event,Medium
10197,3161,2025-02-12 22:04:00,MAIN_BLOCK,FLOOR2,Code Studio,60,650.88,NaN,60.00,47.00,3.39,-75.0,Sunny,No_Event,Low
10198,971,2025-12-23 09:34:00,MAIN_BLOCK,GROUND,Library,141,1355.90,72.45,39.75,99.65,3.47,-37.0,Rainy,FlashMob,Medium
10199,3913,2025-11-24 09:44:00,MECH_BLOCK,FLOOR2,Lab,139,1224.55,73.55,40.25,98.35,4.15,-69.0,Cloudy,FlashMob,Medium

In [ ]:
print("="*60)
print("COLUMN NAMES")
print("="*60)

print(df.columns.tolist())

============================================================
COLUMN NAMES
============================================================
['Record_ID', 'Timestamp', 'Building', 'Floor', 'Zone', 'Connected_Users', 'Bandwidth_Usage_MB', 'Download_Speed_Mbps', 'Upload_Speed_Mbps', 'Latency_ms', 'Packet_Loss_Percent', 'Signal_Strength_dBm', 'Weather', 'Event_Occurring', 'Congestion_Status']

In [ ]:
print("="*60)
print("DATASET INFORMATION")
print("="*60)

df.info()

============================================================
DATASET INFORMATION
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Record_ID            10200 non-null  int64
 1   Timestamp            10200 non-null  object
 2   Building             10200 non-null  object
 3   Floor                10200 non-null  object
 4   Zone                 10200 non-null  object
 5   Connected_Users      10200 non-null  int64
 6   Bandwidth_Usage_MB   10200 non-null  float64
 7   Download_Speed_Mbps  9893 non-null   float64
 8   Upload_Speed_Mbps    10200 non-null  float64
 9   Latency_ms           10200 non-null  float64
 10  Packet_Loss_Percent  10200 non-null  float64
 11  Signal_Strength_dBm  9995 non-null   float64
 12  Weather              10200 non-null  object
 13  Event_Occurring      10200 non-null  object
 14  Congestion_Status    10200 non-null  object
dtypes: float64(6), int64(2), object(7)
memory usage: 1.2+ MB

In [ ]:
print("="*60)
print("STATISTICAL SUMMARY")
print("="*60)

display(df.describe())

============================================================
STATISTICAL SUMMARY
============================================================

,Record_ID,Connected_Users,Bandwidth_Usage_MB,Download_Speed_Mbps,Upload_Speed_Mbps,Latency_ms,Packet_Loss_Percent,Signal_Strength_dBm
count,10200.000000,10200.000000,10200.000000,9893.000000,10200.000000,10200.000000,10200.000000,9995.000000
mean,4997.155882,113.280588,1184.489975,88.943900,47.079706,81.632382,3.776919,-57.876638
std,2887.039983,63.065861,737.156668,30.441568,14.370777,40.992809,1.377070,13.043273
min,1.000000,40.000000,243.280000,8.000000,5.000000,34.000000,1.340000,-80.000000
25%,2500.750000,69.000000,679.260000,74.100000,40.750000,52.850000,2.860000,-69.000000
50%,4995.500000,99.000000,994.440000,95.550000,50.250000,72.350000,3.530000,-58.000000
75%,7500.250000,137.000000,1450.817500,112.050000,57.750000,97.050000,4.380000,-47.000000
max,10000.000000,517.000000,6298.610000,128.000000,65.000000,344.050000,12.230000,-36.000000

In [ ]:
print("="*60)
print("MISSING VALUES")
print("="*60)

missing_values = df.isnull().sum()

display(missing_values)

============================================================
MISSING VALUES
============================================================

Record_ID                0
Timestamp                0
Building                 0
Floor                    0
Zone                     0
Connected_Users          0
Bandwidth_Usage_MB       0
Download_Speed_Mbps    307
Upload_Speed_Mbps        0
Latency_ms               0
Packet_Loss_Percent      0
Signal_Strength_dBm    205
Weather                  0
Event_Occurring          0
Congestion_Status        0
dtype: int64

In [ ]:
print("="*60)
print("DUPLICATE RECORDS")
print("="*60)

duplicates = df.duplicated().sum()

print(f"Total Duplicate Rows: {duplicates}")

============================================================
DUPLICATE RECORDS
============================================================
Total Duplicate Rows: 200

In [ ]:
print("="*60)
print("UNIQUE BUILDINGS")
print("="*60)

print(df["Building"].unique())

print("\n")

print("="*60)
print("UNIQUE EVENTS")
print("="*60)

print(df["Event_Occurring"].unique())

print("\n")

print("="*60)
print("CONGESTION LEVELS")
print("="*60)

print(df["Congestion_Status"].unique())

============================================================
UNIQUE BUILDINGS
============================================================
['AMENITY' 'MECH_BLOCK' 'MARIO' 'AI_BLOCK' 'MAIN_BLOCK' 'BUS_AREA'
 'HOSTEL_GIRLS' 'HOSTEL_BOYS']


============================================================
UNIQUE EVENTS
============================================================
['Culturals' 'No_Event' 'Freshwarite' 'Thiran' 'FlashMob']


============================================================
CONGESTION LEVELS
============================================================
['Medium' 'Low' 'High']

In [ ]:
print("="*60)
print("CONGESTION DISTRIBUTION")
print("="*60)

display(df["Congestion_Status"].value_counts())

============================================================
CONGESTION DISTRIBUTION
============================================================

Congestion_Status
Low       5156
Medium    3732
High      1312
Name: count, dtype: int64

## Observations

1. The dataset contains more than 10,000 records and 15 columns.
2. Missing values are present in:
   - Download_Speed_Mbps
   - Signal_Strength_dBm
3. Duplicate records are intentionally present in the dataset.
4. The dataset contains multiple campus locations such as:
   - Main Block
   - AI Block
   - Mech Block
   - Hostels
   - Amenity Centre
5. Congestion levels are categorized into:
   - Low
   - Medium
   - High
6. The dataset is suitable for data cleaning, SQL analysis, ETL processing, PySpark transformations, machine learning, and AI-based analytics.

# Section 2: Data Cleaning and Preprocessing

In this section, the dataset is cleaned to improve data quality.

The following preprocessing steps are performed:

1. Handling missing values
2. Removing duplicate records
3. Verifying data types
4. Creating a cleaned dataset
5. Saving the cleaned dataset as a new CSV file

This cleaned dataset will be used in subsequent SQL, ETL, PySpark, and Machine Learning tasks.

In [ ]:
df_clean = df.copy()

print("Dataset copied successfully")
print(f"Shape: {df_clean.shape}")

Dataset copied successfully
Shape: (10200, 15)

In [ ]:
print("="*60)
print("MISSING VALUES BEFORE CLEANING")
print("="*60)

display(df_clean.isnull().sum())

============================================================
MISSING VALUES BEFORE CLEANING
============================================================

Record_ID                0
Timestamp                0
Building                 0
Floor                    0
Zone                     0
Connected_Users          0
Bandwidth_Usage_MB       0
Download_Speed_Mbps    307
Upload_Speed_Mbps        0
Latency_ms               0
Packet_Loss_Percent      0
Signal_Strength_dBm    205
Weather                  0
Event_Occurring          0
Congestion_Status        0
dtype: int64

In [ ]:
df_clean["Download_Speed_Mbps"] = df_clean[
    "Download_Speed_Mbps"
].fillna(
    df_clean["Download_Speed_Mbps"].median()
)

print("Download Speed Missing Values Handled")

Download Speed Missing Values Handled

In [ ]:
df_clean["Signal_Strength_dBm"] = df_clean[
    "Signal_Strength_dBm"
].fillna(
    df_clean["Signal_Strength_dBm"].median()
)

print("Signal Strength Missing Values Handled")

Signal Strength Missing Values Handled

In [ ]:
print("="*60)
print("MISSING VALUES AFTER CLEANING")
print("="*60)

display(df_clean.isnull().sum())

============================================================
MISSING VALUES AFTER CLEANING
============================================================

Record_ID              0
Timestamp              0
Building               0
Floor                  0
Zone                   0
Connected_Users        0
Bandwidth_Usage_MB     0
Download_Speed_Mbps    0
Upload_Speed_Mbps      0
Latency_ms             0
Packet_Loss_Percent    0
Signal_Strength_dBm    0
Weather                0
Event_Occurring        0
Congestion_Status      0
dtype: int64

In [ ]:
print("="*60)
print("DUPLICATE RECORDS BEFORE CLEANING")
print("="*60)

duplicates_before = df_clean.duplicated().sum()

print(f"Duplicate Rows: {duplicates_before}")

============================================================
DUPLICATE RECORDS BEFORE CLEANING
============================================================
Duplicate Rows: 200

In [ ]:
df_clean.drop_duplicates(inplace=True)
print("Duplicate Records Removed")

Duplicate Records Removed

In [ ]:
print("="*60)
print("DUPLICATE RECORDS AFTER CLEANING")
print("="*60)

duplicates_after = df_clean.duplicated().sum()

print(f"Duplicate Rows: {duplicates_after}")

============================================================
DUPLICATE RECORDS AFTER CLEANING
============================================================
Duplicate Rows: 0

In [ ]:
print("="*60)
print("DATA TYPES")
print("="*60)

display(df_clean.dtypes)

============================================================
DATA TYPES
============================================================

Record_ID                int64
Timestamp               object
Building                object
Floor                   object
Zone                    object
Connected_Users          int64
Bandwidth_Usage_MB     float64
Download_Speed_Mbps    float64
Upload_Speed_Mbps      float64
Latency_ms             float64
Packet_Loss_Percent    float64
Signal_Strength_dBm    float64
Weather                 object
Event_Occurring         object
Congestion_Status       object
dtype: object

In [ ]:
df_clean["Timestamp"] = pd.to_datetime(
    df_clean["Timestamp"]
)

print("Timestamp converted to datetime")

Timestamp converted to datetime

In [ ]:
print(df_clean["Timestamp"].dtype)

datetime64[ns]

In [ ]:
print("="*60)
print("FINAL CLEANED DATASET SHAPE")
print("="*60)

print(df_clean.shape)

============================================================
FINAL CLEANED DATASET SHAPE
============================================================
(10000, 15)

In [ ]:
display(df_clean.head())

,Record_ID,Timestamp,Building,Floor,Zone,Connected_Users,Bandwidth_Usage_MB,Download_Speed_Mbps,Upload_Speed_Mbps,Latency_ms,Packet_Loss_Percent,Signal_Strength_dBm,Weather,Event_Occurring,Congestion_Status
0,1,2025-09-12 01:18:00,AMENITY,GROUND,Music Room,100,1137.17,95.00,50.00,73.00,3.39,-58.0,Rainy,Culturals,Medium
1,2,2025-03-02 18:18:00,MECH_BLOCK,GROUND,FABLAB,63,747.05,115.35,59.25,48.95,1.87,-57.0,Sunny,No_Event,Low
2,3,2025-05-19 05:21:00,MARIO,GROUND,Snack Corner,115,1323.06,86.75,46.25,82.75,2.81,-58.0,Sunny,No_Event,Medium
3,4,2025-04-19 20:10:00,AI_BLOCK,FLOOR3,Data Visualization Lab,94,1395.81,98.30,51.50,69.10,3.31,-44.0,Rainy,No_Event,Low
4,5,2025-12-06 22:12:00,MAIN_BLOCK,FLOOR2,IT Project Lab,57,828.78,118.65,60.75,45.05,3.57,-72.0,Sunny,Freshwarite,Low

In [ ]:
df_clean.to_csv(
    "campus_wifi_cleaned.csv",
    index=False
)

print("Cleaned Dataset Saved Successfully")
print("File Name: campus_wifi_cleaned.csv")

Cleaned Dataset Saved Successfully
File Name: campus_wifi_cleaned.csv

## Observations

1. Missing values in Download_Speed_Mbps were replaced using the median value.
2. Missing values in Signal_Strength_dBm were replaced using the median value.
3. Duplicate records were successfully removed.
4. Timestamp column was converted into datetime format.
5. The cleaned dataset was exported as campus_wifi_cleaned.csv.
6. The cleaned dataset is now ready for SQLite database integration and SQL analysis.